#!/usr/bin/env python
import argparse
import json
import os
import re
import subprocess
import sys

JSON_PATH = "resource/url_dict.json"


def format_url(url):
    if not re.match('(?:http|ftp|https)://', url):
        return 'http://{}'.format(url)
    return url


def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--add", "-a", dest="add", nargs=2)
    parser.add_argument("url_list", nargs=argparse.REMAINDER)
    parser.add_argument("--list", "-l", action=argparse.BooleanOptionalAction)
    args = parser.parse_args()
    return args


if __name__ == "__main__":
    args = get_args()

    if not os.path.exists(JSON_PATH):
        url_dict = dict()
    else:
        with open(JSON_PATH) as f:
            url_dict = json.load(f)

    if args.list:
        print('{:>8} {:>8}'.format("shortcut", "url"))
        for k, v in url_dict.items():
            print('{:>8} {:>8}'.format(k, v))
        sys.exit(0)

    if args.add:
        url_dict[args.add[0]] = args.add[1]
        with open(JSON_PATH, 'w') as f:
            json.dump(url_dict, f)

    if args.url_list:
        for url in args.url_list:
            _url = format_url(url_dict.get(url, url))
            subprocess.run(["open", "-a", "Google Chrome", _url])
    else:
        if not args.add:
            subprocess.run(["open", "-a", "Google Chrome",
                           "https://courseworks2.columbia.edu"])
