#! /usr/bin/python3
# -*- coding: utf-8 -*-
'''
Author  :   xc
Email   :   xckomorebi@icloud.com
Date    :   2020.11.20
'''
import sys
import random
import argparse
import urllib.request
import json
import webbrowser

# url = 'https://www.bilibili.com/video/BV1wK411V7dW' # testing


def bvid2aid(bvid):
    """
    BV号转AV号
    代码来源：https://www.zhihu.com/question/381784377/answer/1099438784
    :param bvid:
    :return:
    """
    table = 'fZodR9XQDSUm21yCkr6zBqiveYah8bt4xsWpHnJE7jL5VG3guMTKNPAwcF'
    tr = {}
    for i in range(58):
        tr[table[i]] = i
    s = [11, 10, 3, 8, 4, 6]
    xor = 177451812
    add = 8728348608

    def dec(x):
        r = 0
        for i in range(6):
            r += tr[x[s[i]]] * 58 ** i
        return (r - add) ^ xor

    return dec(bvid)


def get_comments(url):
    try:
        bvid = url.split('/')[-1]
        oid = bvid2aid(bvid)
    except IndexError:
        print("Error: 无法解析该url, 请确认是b站视频链接")
        sys.exit()

    api = 'https://api.bilibili.com/x/v2/reply?type=1&oid='
    # should not hardcode, but whatever... it works

    try:
        resp = urllib.request.urlopen(api+str(oid))
        data = json.loads(resp.read()).get('data')
        comments = data.get('replies')
    except urllib.error.URLError:
        print("Error: 无法获得评论, 请查看网络连接情况")
        sys.exit()
    return comments


def comments_filter(comment):
    member = comment.get('member')
    return (member.get('mid'), member.get('uname'))


def open_space_from_uids(uids):
    for uid in uids:
        url = 'https://space.bilibili.com/' + uid
        webbrowser.open(url)


def roll_from_comments(url, num=1):
    if args.num:
        num = int(args.num)
    comments = get_comments(url)
    uids = list(set(map(comments_filter, comments)))

    if num > len(uids):
        raise ValueError("抽取观众数量大于评论数")

    lucky = random.choices(uids, k=num)
    lucky_uids = []
    lucky_unames = []

    for (uid, uname) in lucky:
        lucky_uids.append(uid)
        lucky_unames.append(uname)

    if num == 1:
        print("🎉🎉🎉恭喜 {} 中奖".format(''.join(lucky_unames)))
    else:
        print("🎉🎉🎉恭喜 {0} {1}位幸运观众中奖".format(", ".join(lucky_unames), len(lucky_unames)))
    return lucky_uids


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('url', help="视频的链接")
    parser.add_argument('--num', '-n', help="指定获奖的人数, 默认为1")
    args = parser.parse_args()

    url = args.url
    lucky_uids = roll_from_comments(url)

    if input("是否查看TA的b站空间(按y确定):") == "y":
        open_space_from_uids(lucky_uids)
