#!/usr/bin/env bash

alacritty_config_path=~/.config/alacritty/alacritty.toml

if [ -h $alacritty_config_path ]; then
  alacritty_config_path=$(readlink $alacritty_config_path)
fi

opacity=$(awk '$1 == "opacity" {print $3; exit}' \
    $alacritty_config_path)

case $opacity in
  1)
    toggle_opacity=0.64
    ;;
  0.0)
    exit 0
    ;;
  *)
    toggle_opacity=1
    ;;
esac

sed -i "s/opacity = $opacity/opacity = $toggle_opacity/" \
   $alacritty_config_path
