#! /bin/bash

amount=1

if [ $# -ge 1 ]; then
    amount=$1
fi

url="https://min-api.cryptocompare.com/data/price?fsym=USD&tsyms=CNY"
rate=$(curl -s "$url" | jq -r '.CNY')
echo "scale=4; $amount * $rate" | bc
